import type { Metadata } from "next";
import { Inter,Libre_Baskerville } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";



const inter = Inter({ 
  subsets: ["latin"],
  variable:'--font-inter'
});


const libreBaskerville = Libre_Baskerville({
  weight: ['400', '700'], // Puedes especificar más de un peso si lo necesitas
  subsets: ['latin', 'latin-ext'],
  variable: '--font-baskerville'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.variable} ${libreBaskerville.variable}`}>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}